<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends CommonSiteRepository
{
	public function getAvecCategories(array $nom_categories)
    {
		$qb = $this->createQueryBuilder('a');
	 
		// On fait une jointure avec l'entité Categorie, avec pour alias « c »
		$qb ->join('a.categories', 'c')
			->where($qb->expr()->in('c.nom', $nom_categories)); // Puis on filtre sur le nom des catégories à l'aide d'un IN
	 
		// Enfin, on retourne le résultat
		return $qb->getQuery()->getResult();
    }
	
	public function getSelectList()
    {
		$qb = $this->createQueryBuilder('a')
               ->where('a.publication = 1'); // On filtre sur l'attribut publication
 
		// Et on retourne simplement le QueryBuilder, et non la Query, attention
		return $qb;
    }
	
	protected function getAllEntities()
    {
		$query = $this->createQueryBuilder('a')
					  ->leftJoin('a.image', 'i')
						->addSelect('i')
					  ->leftJoin('a.categories', 'cat')
						->addSelect('cat')
					  ->orderBy('a.date', 'DESC')
					  ->getQuery();
					  
		return $query;
	}
	
	protected function getAllPublishedEntities()
    {
		$query = getAllEntities();
		$query->add('where', 'a.publication = 1');
					  
		return $query->getQuery();
	}
}
