<?php

namespace Sdz\BlogBundle\Entity;

/**
 * EcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoleRepository extends CommonSiteRepository
{
	protected function getAllEntities()
    {
		$query = $this->createQueryBuilder('e')
					  ->orderBy('e.dateEntree', 'DESC')
					  ->leftJoin('e.logo', 'l')
					  ->addSelect('l');
		return $query->getQuery();
	}
	
	protected function getAllPublishedEntities()
    {
		$query = $this->createQueryBuilder('e')
					  ->orderBy('e.dateEntree', 'DESC')
					  ->leftJoin('e.logo', 'l')
					  ->addSelect('l')
					  ->add('where', 'e.publication = 1');
					  
		return $query->getQuery();
	}
}
