<?php

namespace Sdz\BlogBundle\Entity;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends CommonSiteRepository
{
    protected function getAllEntities()
    {
		$query = $this->createQueryBuilder('f')
					  ->leftJoin('f.periode', 'p')
					  ->addSelect('p')
		              ->orderBy('p.dateDebut', 'DESC');
		return $query->getQuery();
	}
	
	protected function getAllPublishedEntities()
    {
		$query = $this->createQueryBuilder('f')
					  ->leftJoin('f.periode', 'p')
					  	->addSelect('p')
		              ->orderBy('p.dateDebut', 'DESC')
					  ->add('where', 'f.publication = 1');
					  
		return $query->getQuery();
	}
}
