<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
	public function getAllPage()
	{
		$query = $this->createQueryBuilder('p')
					  ->orderBy('p.visits', 'DESC');
		return $query->getQuery()->execute();
	}
}
