<?php

namespace Sdz\BlogBundle\Entity;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteCommentRepository  extends CommonSiteRepository
{
	protected function getAllEntities()
    {
		$query = $this->createQueryBuilder('s')
		              ->orderBy('s.date', 'DESC');		  
		return $query->getQuery();
	}
	
	protected function getAllPublishedEntities()
    {
		$query = $this->createQueryBuilder('s')
		              ->orderBy('s.date', 'DESC')
					  ->add('where', 's.publication = 1');
					  
		return $query->getQuery();
	}
}
