<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TechnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnoRepository extends CommonSiteRepository
{
    protected function getAllEntities()
    {
		$query = $this->createQueryBuilder('t')->orderBy('t.level', 'ASC');
		return $query->getQuery();
    }
   
    protected function getAllPublishedEntities()
    {
		$query = $this->createQueryBuilder('t')
					  ->orderBy('t.level', 'ASC')
					  ->add('where', 't.publication = 1');
					  
		return $query->getQuery();
	}
}
