<?php

namespace Sdz\BlogBundle\Entity;

/**
 * TheatreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheatreRepository extends CommonSiteRepository
{
	protected function getAllEntities()
    {
		$query = $this->createQueryBuilder('t')->orderBy('t.dateDebut', 'DESC');
		return $query->getQuery();
	}
	
	protected function getAllPublishedEntities()
    {
		$query = $this->createQueryBuilder('t')
					  ->orderBy('t.dateDebut', 'DESC')
					  ->add('where', 't.publication = 1');
					  
		return $query->getQuery();
	}
}
